// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpjjtajbsnnphszojggs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpwamp0YWpic25ucGhzem9qZ2dzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNDA3NjksImV4cCI6MjA2MzgxNjc2OX0.uD6NE0wFkbperFIyaTJ1LFJ7xDgVOoFjPmNDY9cKAuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);